import { DOCUMENT } from '@angular/common';
import { Inject, Injectable, signal } from '@angular/core';

export type SiteLanguage = 'en' | 'tcz';

const storageKey = 'pbc-language';

const translations = {
  en: {
    'language.toggleLabel': 'Language',
    'language.english': 'English',
    'language.thadou': 'Thadou',
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.whoWeAre': 'Who We Are',
    'nav.staff': 'Staff',
    'nav.bylaws': 'Bylaws',
    'nav.ministries': 'Ministries',
    'nav.overview': 'Overview',
    'nav.mission': 'Mission',
    'nav.men': 'Men',
    'nav.women': 'Women',
    'nav.khanglai': 'Khanglai',
    'nav.children': 'Children',
    'nav.sermons': 'Sermons',
    'nav.songbook': 'Songbook',
    'nav.contact': 'Contact',
    'nav.give': 'Give',
    'nav.menu': 'Menu',
    'home.welcome': 'Welcome',
    'home.motto': "Peniel Baptist Church is committed to reach and teach the Gospel with Jesus' love and compassion.",
    'home.planVisit': 'Plan a Visit',
    'home.giveOnline': 'Give Online',
    'home.sundayWorship': 'Sunday Worship',
    'home.englishWorship': 'English Worship',
    'home.wednesdayBibleStudy': 'Wednesday Bible Study',
    'home.thirdSunday': '3rd Sunday',
    'home.media': 'Media',
    'home.recentTeaching': 'Recent worship and teaching',
    'home.mediaCopy': 'Follow along with recent services and messages from the church YouTube channel.',
    'home.openYoutube': 'Open YouTube Channel',
    'home.listenPodcast': 'Listen to Podcast',
    'home.connect': 'Connect',
    'home.nextTitle': 'Find what you need next',
    'home.community':
      'PBC Tulsa is mainly a Thadou-speaking community church, with English worship service every third Sunday.',
    'home.contactCta': 'Visit, get directions, and see service times',
    'home.ministriesDetail': 'Explore men, women, Khanglai, children, and mission',
    'home.sermonsDetail': 'Watch and listen to recent messages',
    'home.songbookDetail': 'Search lyrics and worship songs',
    'home.contactDetail': 'Get directions, phone, and service info',
    'about.eyebrow': 'About',
    'about.title': 'About',
    'about.lead':
      "Peniel Baptist Church is committed to reach and teach the Gospel with Jesus' love and compassion. We are a mainly Thadou-speaking Baptist church in Tulsa, shaped by worship, evangelism, ministry, discipleship, and fellowship.",
    'about.missionTitle': 'Mission',
    'about.missionText':
      "Peniel Baptist Church is committed to reach and teach the Gospel with Jesus' love and compassion.",
    'about.visionTitle': 'Vision',
    'about.visionText':
      'Peniel Baptist Church aims to build up a strong missional church for evangelism works to accomplish the Great Commission of Jesus Christ.',
    'about.beliefEyebrow': 'What We Believe',
    'about.beliefTitle': 'Rooted in Scripture and centered on Christ',
    'about.beliefText':
      'We affirm the Holy Bible as the inspired Word of God and the foundation for our faith. As a Baptist church, we receive The Baptist Faith and Message as a general statement of our beliefs.',
    'about.belief1Label': 'Scripture',
    'about.belief1Title': 'The Bible is our foundation',
    'about.belief1Text':
      'We affirm the Holy Bible as God-inspired and the basis for what we believe, teach, and practice.',
    'about.belief2Label': 'Mission',
    'about.belief2Title': 'Great Commandment and Great Commission',
    'about.belief2Text':
      'We seek to love God, love our neighbors, make disciples, and share the Gospel of Jesus Christ.',
    'about.belief3Label': 'Formation',
    'about.belief3Title': 'Growing as disciples',
    'about.belief3Text':
      'We gather for worship, learn together, serve with our gifts, and encourage one another toward faithful living.',
    'about.belief4Label': 'Community',
    'about.belief4Title': 'A welcoming church family',
    'about.belief4Text':
      'We want every person and family who visits to be received warmly and pointed toward life in Christ.',
    'about.lifeEyebrow': 'Church Life',
    'about.lifeTitle': 'A family called to worship, serve, and welcome',
    'about.lifeText1':
      "Our members commit to protect the unity of the church, share responsibility for its growth, serve with their gifts, and support the church's witness through faithful worship and godly living.",
    'about.lifeText2':
      'We serve the Tulsa Metropolitan Area, including Asian immigrant families, and welcome people without discrimination because of race, color, national origin, disability, age, or sex.',
    'about.affiliationText':
      'is autonomous and voluntarily cooperates with the Southern Baptist Convention, the Baptist General Convention of Oklahoma, and the Tulsa Metro Baptist Association.',
    'about.bylawsNote': 'The current bylaws and policy document was approved January 11, 2026.',
    'about.bylawsButton': 'View and Download Bylaws',
    'ministries.eyebrow': 'Ministries',
    'ministries.title': 'Church ministries',
    'ministries.back': 'Back to ministries',
    'ministries.bylawFocus': 'Bylaw focus',
    'ministries.emphasis': 'What this ministry emphasizes',
    'ministries.socialUpdates': 'Social updates',
    'ministries.socialIntro':
      'Recent ministry posts appear here as native cards, so the layout matches the rest of the site.',
    'ministries.openFacebook': 'Open Facebook',
    'ministries.openInstagram': 'Open Instagram',
    'ministries.loading': 'Loading ministry updates...',
    'ministries.noPosts': 'No recent posts available yet.',
    'ministries.socialImageAlt': 'Social update image',
    'ministries.openPostFallback': 'Open the post to view the latest update.',
    'ministries.openPost': 'Open post',
    'ministries.notFound': 'Ministry not found.',
    'ministries.lead':
      'These ministries are organized to help our church live out the Gospel through worship, teaching, fellowship, service, and discipleship.',
    'ministries.feedError': 'Unable to load ministry updates.',
    'songbook.eyebrow': 'Church Songbook',
    'songbook.title': 'PBC Songbook',
    'songbook.lead': 'Search by title, number, author, song type, or lyrics.',
    'songbook.allSongType': 'All Song Type',
    'songbook.shown': 'shown',
    'songbook.total': 'total',
    'songbook.searchSongs': 'Search songs',
    'songbook.songType': 'Song type',
    'songbook.clear': 'Clear',
    'songbook.loading': 'Loading songbook...',
    'songbook.noMatches': 'No songs match the current search.',
    'songbook.unknownAuthor': 'Unknown author',
    'songbook.loadError': 'Unable to load songs from Cloudflare.',
    'staff.eyebrow': 'Leadership',
    'staff.title': 'Staff and church officers',
    'staff.lead': 'Current staff and officers, with leadership term history from the church database.',
    'staff.department': 'Department',
    'staff.loading': 'Loading staff...',
    'staff.noStaff': 'No staff found for this department.',
    'staff.viewPreviousTerms': 'View previous terms',
    'staff.viewCurrentStaff': 'View current staff',
    'staff.fallbackMessage': 'Showing local staff data until Cloudflare staff data is available.',
    'staff.allDepartments': 'All',
    'staff.churchExecutive': 'Church Executive',
    'staff.previousStaff': 'Previous Staff',
    'staff.allStaff': 'All Staff',
    'contact.eyebrow': 'Contact',
    'contact.title': 'Visit or contact',
    'contact.address': 'Address',
    'contact.serviceTimes': 'Service Times',
    'contact.memberLinks': 'Member Links',
    'contact.bulletin': 'Bulletin',
    'contact.calendar': 'Church Calendar',
    'contact.directory': 'Church Directory',
    'contact.followOnline': 'Follow Online',
    'contact.sundayWorshipService': 'Sunday Worship Service',
    'contact.englishWorshipService': 'English Worship Service',
    'contact.wednesdayBibleStudy': 'Wednesday Bible Study',
    'sermons.eyebrow': 'Sermons',
    'sermons.title': 'Sermons and live worship',
    'sermons.lead': 'Use this page for sermon archives, livestream embeds, podcast links, and worship media.',
    'bylaws.eyebrow': 'Governance',
    'bylaws.title': 'Bylaws and policy',
    'bylaws.leadPrefix': 'View or download the current',
    'bylaws.leadSuffix': 'bylaws and policy document approved January 11, 2026.',
    'bylaws.viewPdf': 'View PDF',
    'bylaws.download': 'Download Bylaws',
    'footer.contactUs': 'Contact Us',
    'footer.follow': 'Follow',
    'footer.rights': 'All rights reserved.'
  },
  tcz: {
    "language.toggleLabel": "Sapao",
    "language.english": "English",
    "language.thadou": "Thadou",
    "nav.home": "Inpi",
    "nav.about": "Ithu-le-hla",
    "nav.whoWeAre": "I-hi-u-hi",
    "nav.staff": "Staff",
    "nav.bylaws": "Dan-le-thupeh",
    "nav.ministries": "Kivaihomna",
    "nav.overview": "A-kim-a-kim",
    "nav.mission": "Mission",
    "nav.men": "Pathen-pa",
    "nav.women": "Pathen-nu",
    "nav.khanglai": "Khanglai",
    "nav.children": "Naopang",
    "nav.sermons": "Thu-le-la",
    "nav.songbook": "La-bu",
    "nav.contact": "Be-ding",
    "nav.give": "Peh-ding",
    "nav.menu": "Menu",
    "home.welcome": "Chibai",
    "home.motto": "Peniel Baptist Church in Jesun itna le lainatna toh Gospel thupha hi phondoh le hil-dingin kitem ahi.",
    "home.planVisit": "Kave-dingin kigong-in",
    "home.giveOnline": "Online-a peh-ding",
    "home.sundayWorship": "Pathianni Houin",
    "home.englishWorship": "English-a Houin",
    "home.wednesdayBibleStudy": "Nilai-ni Bible Study",
    "home.thirdSunday": "Pathianni 3-na",
    "home.media": "Media",
    "home.recentTeaching": "Houin-le-thuhilna thah-ho",
    "home.mediaCopy": "Church YouTube channel-a kitho-le-thuhilna thah-ho en-in.",
    "home.openYoutube": "YouTube Channel hon-in",
    "home.listenPodcast": "Podcast ngaithlak-ding",
    "home.connect": "Kikah-ding",
    "home.nextTitle": "Na-dei-ho mu-dingin",
    "home.community": "PBC Tulsa hi Thadou-paong-a houin-a kikhawm-ho ahi-uvin, Pathianni 3-na teng English-in houin-a kikhawm-u ahi.",
    "home.contactCta": "Ve-in, lampi-le-houin hun-ho en-in",
    "home.ministriesDetail": "Pathen-pa, Pathen-nu, Khanglai, naopang, le mission-ho en-in",
    "home.sermonsDetail": "Thuhilna thah-ho en-in ngaithla-in",
    "home.songbookDetail": "La-thu-ho zong-in",
    "home.contactDetail": "Lampi, phone, le houin-hun-ho kicheh-tah-in",
    "about.eyebrow": "Ithu-le-hla",
    "about.title": "Ithu-le-hla",
    "about.lead": "Peniel Baptist Church in Jesun itna le lainatna toh Gospel thupha hi phondoh le hil-dingin kitem ahi. Ihi-u hi Tulsa-a Thadou-paong-a houin-a kikhawm Baptist houin khat ihi-uvin, houin, thuhilna, kivaihomna, le kithu-kikah-na-a kigong ihi-u ahi.",
    "about.missionTitle": "Mission",
    "about.missionText": "Peniel Baptist Church in Jesun itna le lainatna toh Gospel thupha hi phondoh le hil-dingin kitem ahi.",
    "about.visionTitle": "Vision",
    "about.visionText": "Peniel Baptist Church in Jesun Christ-in thu-peh a-peh-ho hi a-kim-a-kim-a a-tup-dingin mission-a kigong houin hat-tah khat sem-ding a-tup ahi.",
    "about.beliefEyebrow": "I-gin-u",
    "about.beliefTitle": "Bible-a kiphut le Christ-a kigong",
    "about.beliefText": "I-gin-u le i-hil-u hi Bible-a kiphut ahi. Baptist houin khat ihi-u-in, The Baptist Faith and Message hi i-gin-u-a kigong ahi.",
    "about.belief1Label": "Bible",
    "about.belief1Title": "Bible hi i-phut-u ahi",
    "about.belief1Text": "Bible hi Pathen-in a-se-a kigong, i-gin-u le i-hil-u-a kiphut ahi.",
    "about.belief2Label": "Mission",
    "about.belief2Title": "Thupeh-li-le-thupeh-len",
    "about.belief2Text": "Pathen-it-ding, i-veng-u it-ding, le Jesun Christ Gospel hi phondoh-ding i-tup-u ahi.",
    "about.belief3Label": "Kithu-kikah-na",
    "about.belief3Title": "Disciples-a kithang-len",
    "about.belief3Text": "Houin-a kikhawm-in, kithu-hil-in, le kithu-kikah-in i-kithang-len-u ahi.",
    "about.belief4Label": "Community",
    "about.belief4Title": "Houin-chate-khat",
    "about.belief4Text": "Mi-tin-in houin-a a-hung-u-hi chibai-buk-in, Christ-a hin-na-a kikai-lut-ding i-tup-u ahi.",
    "about.lifeEyebrow": "Houin-hin-na",
    "about.lifeTitle": "Houin-a kikhawm, kithu-kikah, le chibai-buk-ding-a kigong",
    "about.lifeText1": "I-houin-u hi kithu-kikah-na-a kithang-len, kithu-kikah-na-a kithang-len, le Pathen-a kithang-len-ding i-kitem-u ahi.",
    "about.lifeText2": "Tulsa-a cheng-ho, Asian-ho, le mi-tin-ho, chibai-buk-in, mi-khat-le-khat-a kithu-kikah-na-a kithang-len-u ahi.",
    "about.affiliationText": "Southern Baptist Convention, Baptist General Convention of Oklahoma, le Tulsa Metro Baptist Association-ho toh kithu-kikah-in kithang-len-u ahi.",
    "about.bylawsNote": "Dan-le-thupeh hi January 11, 2026-a kigong ahi.",
    "about.bylawsButton": "Dan-le-thupeh en-in",
    "ministries.eyebrow": "Kivaihomna",
    "ministries.title": "Houin-kivaihomna",
    "ministries.back": "Kivaihomna-a kile-ding",
    "ministries.bylawFocus": "Dan-le-thupeh",
    "ministries.emphasis": "Kivaihomna-a kigong-ho",
    "ministries.socialUpdates": "Social updates",
    "ministries.socialIntro": "Houin-a kitho-ho hi hiche-a hi mu-thei ahi.",
    "ministries.openFacebook": "Facebook hon-in",
    "ministries.openInstagram": "Instagram hon-in",
    "ministries.loading": "Kivaihomna-ho kigong-lai...",
    "ministries.noPosts": "Post-ho kigong-lai-poi.",
    "ministries.socialImageAlt": "Social update image",
    "ministries.openPostFallback": "Post-ho en-in.",
    "ministries.openPost": "Post hon-in",
    "ministries.notFound": "Kivaihomna mu-thei-poi.",
    "ministries.lead": "Kivaihomna-ho hi houin-a kitho-ding-a kigong ahi.",
    "ministries.feedError": "Kivaihomna-ho kigong-thei-poi.",
    "songbook.eyebrow": "La-bu",
    "songbook.title": "PBC La-bu",
    "songbook.lead": "La-bu-a la-ho zong-in.",
    "songbook.allSongType": "La-tin",
    "songbook.shown": "mu-thei",
    "songbook.total": "a-kim-a-kim",
    "songbook.searchSongs": "La-ho zong-in",
    "songbook.songType": "La-nam",
    "songbook.clear": "Clear",
    "songbook.loading": "La-bu kigong-lai...",
    "songbook.noMatches": "La-ho mu-thei-poi.",
    "songbook.unknownAuthor": "Author-ho kisei-poi",
    "songbook.loadError": "Cloudflare-a la-ho kigong-thei-poi.",
    "staff.eyebrow": "Kivaihom-ho",
    "staff.title": "Staff-ho le kivaihom-ho",
    "staff.lead": "Staff-ho le kivaihom-ho-ho.",
    "staff.department": "Department",
    "staff.loading": "Staff-ho kigong-lai...",
    "staff.noStaff": "Staff-ho mu-thei-poi.",
    "staff.viewPreviousTerms": "Staff-ho hlui-ho en-in",
    "staff.viewCurrentStaff": "Staff-ho thah-ho en-in",
    "staff.fallbackMessage": "Staff-ho kigong-lai.",
    "staff.allDepartments": "A-kim-a-kim",
    "staff.churchExecutive": "Church Executive",
    "staff.previousStaff": "Staff-ho hlui-ho",
    "staff.allStaff": "Staff-ho tin",
    "contact.eyebrow": "Be-ding",
    "contact.title": "Ve-in, be-ding",
    "contact.address": "Address",
    "contact.serviceTimes": "Houin-hun-ho",
    "contact.memberLinks": "Member-ho link",
    "contact.bulletin": "Bulletin",
    "contact.calendar": "Houin-calendar",
    "contact.directory": "Houin-directory",
    "contact.followOnline": "Online-a kitho-ding",
    "contact.sundayWorshipService": "Pathianni Houin",
    "contact.englishWorshipService": "English-a Houin",
    "contact.wednesdayBibleStudy": "Nilai-ni Bible Study",
    "sermons.eyebrow": "Thu-le-la",
    "sermons.title": "Thu-le-la le houin-a kitho-ho",
    "sermons.lead": "Thu-le-la-ho hi hiche-a hi mu-thei ahi.",
    "bylaws.eyebrow": "Dan-le-thupeh",
    "bylaws.title": "Dan-le-thupeh",
    "bylaws.leadPrefix": "Dan-le-thupeh hi",
    "bylaws.leadSuffix": "January 11, 2026-a kigong ahi.",
    "bylaws.viewPdf": "PDF en-in",
    "bylaws.download": "Dan-le-thupeh download-in",
    "footer.contactUs": "Be-ding",
    "footer.follow": "Zui-in",
    "footer.rights": "A-kim-a-kim-a kiven-ahi."
  }
} as const;

export type TranslationKey = keyof typeof translations.en;

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  readonly language = signal<SiteLanguage>(this.initialLanguage());

  constructor(@Inject(DOCUMENT) private readonly document: Document) {
    this.applyDocumentLanguage(this.language());
  }

  setLanguage(language: SiteLanguage): void {
    this.language.set(language);
    this.applyDocumentLanguage(language);
    localStorage.setItem(storageKey, language);
  }

  toggleLanguage(): void {
    this.setLanguage(this.language() === 'en' ? 'tcz' : 'en');
  }

  t(key: TranslationKey): string {
    return translations[this.language()][key] || translations.en[key];
  }

  private initialLanguage(): SiteLanguage {
    const stored = localStorage.getItem(storageKey);
    return stored === 'tcz' || stored === 'en' ? stored : 'en';
  }

  private applyDocumentLanguage(language: SiteLanguage): void {
    this.document.documentElement.lang = language;
  }
}
